name: CMake Benchmark
on: [push, pull_request]
env:
  IS_PERFORMANCE_TEST: TRUE

jobs:
  build:
    name: ${{ matrix.os }}.CPP${{ matrix.version }}
    runs-on: ${{ matrix.os }}
    env:
      CMAKE_C_COMPILER: ${{ matrix.cc }})
      CMAKE_CXX_COMPILER: ${{ matrix.cxx }})
      CPP_VERSION: ${{ matrix.version }})

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: ["17", "20"]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: create build environment
      run: |
        cmake -E make_directory ${{ runner.workspace }}/_build
        cmake -E make_directory ${{ runner.workspace }}/Json

    - name: configure cmake
      shell: bash
      working-directory: ${{ runner.workspace }}/_build
      run: cmake -DBENCHMARK_ENABLE_TESTING=OFF -DBENCHMARK_DOWNLOAD_DEPENDENCIES=ON $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Release

    - name: build
      shell: bash
      working-directory: ${{ runner.workspace }}/_build
      run: cmake --build . --config Release

    - name: Run tests
      env:
        BENCHMARK_OUT: ${{ runner.workspace }}/Json/${{ matrix.os }}.CPP${{ matrix.version }}.json
        BENCHMARK_FORMAT: json    
      shell: bash
      working-directory: ${{ runner.workspace }}/_build
      run: ctest -C Release -V --parallel 1

    - name: Save Log
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}.CPP${{ matrix.version }}
        path: ${{ runner.workspace }}/Json/${{ matrix.os }}.CPP${{ matrix.version }}.json
  
  results:
    name: push result
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodule: TRUE

    - uses: FranzDiebold/github-env-vars-action@v1.2.1
    - name: Print environment variables
      run: |
        echo "GITHUB_REPOSITORY_SLUG=$GITHUB_REPOSITORY_SLUG"
        echo "GITHUB_REPOSITORY_OWNER=$GITHUB_REPOSITORY_OWNER"
        echo "GITHUB_REPOSITORY_OWNER_SLUG=$GITHUB_REPOSITORY_OWNER_SLUG"
        echo "GITHUB_REPOSITORY_NAME=$GITHUB_REPOSITORY_NAME"
        echo "GITHUB_REPOSITORY_NAME_SLUG=$GITHUB_REPOSITORY_NAME_SLUG"
        echo "GITHUB_REF_SLUG=$GITHUB_REF_SLUG"
        echo "GITHUB_REF_NAME=$GITHUB_REF_NAME"
        echo "GITHUB_REF_NAME_SLUG=$GITHUB_REF_NAME_SLUG"
        echo "GITHUB_SHA_SHORT=$GITHUB_SHA_SHORT"

    # - uses: FranzDiebold/github-env-vars-action@v1.2.1
    #   run: |
    #     cmake -E cmake -E make_directory ${{ runner.workspace }}/docs/log
    #     cmake -E cmake -E make_directory ${{ runner.workspace }}/docs/log/$CI_RUN_NUMBER

    # - name: setup artifact
    #   uses: actions/download-artifact@v2
    #   with:
    #     name: windows-latest.CPP20
    #     path: ${{ runner.workspace }}/docs/log/$CI_RUN_NUMBER/windows-latest.CPP20.json

    # - name: result artifact upload
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: result
    #     path: ${{ runner.workspace }}/docs/log/$CI_RUN_NUMBER