name: CMake Benchmark
on: [push, pull_request]
env:
  IS_PERFORMANCE_TEST: TRUE

jobs:
  build:
    name: ${{ matrix.os }}.CPP${{ matrix.version }}
    runs-on: ${{ matrix.os }}
    env:
      CMAKE_C_COMPILER: ${{ matrix.cc }})
      CMAKE_CXX_COMPILER: ${{ matrix.cxx }})
      CPP_VERSION: ${{ matrix.version }})

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: ["17", "20"]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: create build environment
      shell: bash
      run: |
        cmake -E make_directory ${{ runner.workspace }}/_build
        cmake -E make_directory ${{ runner.workspace }}/CSV

    - name: configure cmake
      shell: bash
      working-directory: ${{ runner.workspace }}/_build
      run: cmake -DBENCHMARK_ENABLE_TESTING=OFF -DBENCHMARK_DOWNLOAD_DEPENDENCIES=ON $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Release

    - name: build
      shell: bash
      working-directory: ${{ runner.workspace }}/_build
      run: cmake --build . --config Release

    - name: Run tests
      env:
        BENCHMARK_OUT: ${{ runner.workspace }}/CSV/${{ matrix.os }}.CPP${{ matrix.version }}.csv
        BENCHMARK_FORMAT: csv    
      shell: bash
      working-directory: ${{ runner.workspace }}/_build
      run: ctest -C Release -V --parallel 1

    - name: Save Log
      uses: actions/upload-artifact@v2
      with:
        name: CMakeCache
        path: ${{ runner.workspace }}/CSV/${{ matrix.os }}.CPP${{ matrix.version }}.csv
        retention-days: 1